import random
print("╔═══════════════════════════════════════════════════════════════╗")
print("║ 888                                                           ║")
print("║ 888                                                           ║")
print("║ 888                                                           ║")
print("║ 88888b.  8888b. 88888b.  .d88b. 88888b.d88b.  8888b. 88888b.  ║")
print("║ 888  88b     88b888  88bd88P 88b888  888  88b     88b888  88b ║")
print("║ 888  888.d888888888  888888  888888  888  888.d888888888  888 ║")
print("║ 888  888888  888888  888Y88b 888888  888  888888  888888  888 ║")
print("║ 888  888 Y888888888  888  Y88888888  888  888 Y888888888  888 ║")
print("║                              888                              ║")
print("║                         Y8b d88P                              ║")
print("╚═══════════════════════════════════════════════════════════════╝")
input("Aby zaczac, kliknij enter")
words=["kokos", "jablko", "niedzwiedz", "informatyka"]
haslo=random.choice(words)
lifes=10
# print(haslo)
wrd=list(haslo)


# print("      _______")
# print("     |/      |")
# print("     |      (_)")
# print("     |      \|/")
# print("     |       |")
# print("     |      / \.")
# print("     |")
# print("    _|___")

for i in range(len(haslo)):
    wrd[i]="_"

while lifes>0:
    print(' '.join(wrd))
    print("podaj litere:")
    letter=input()
    if letter in haslo:
        for i in range(len(haslo)):
            if haslo[i]==letter:
                wrd[i]=letter
    else:
        lifes=lifes-1
    if lifes==9:
        print("              ")
        print("              ")
        print("               ")
        print("               ")
        print("              ")
        print("               ")
        print("      ")
        print("    _|___")
        print(lifes)
    elif lifes==8:
        print("              ")
        print("     |        ")
        print("     |         ")
        print("     |         ")
        print("     |        ")
        print("     |         ")
        print("     |")
        print("    _|___")
        print(lifes)
    elif lifes==7:
        print("      _______")
        print("     |/      |")
        print("     |         ")
        print("     |         ")
        print("     |        ")
        print("     |         ")
        print("     |")
        print("    _|___")
        print(lifes)
    elif lifes==6:
        print("      _______")
        print("     |/      |")
        print("     |      (_)")
        print("     |         ")
        print("     |        ")
        print("     |         ")
        print("     |")
        print("    _|___")
        print(lifes)
    elif lifes==5:
        print("      _______")
        print("     |/      |")
        print("     |      (_)")
        print("     |       | ")
        print("     |       |")
        print("     |         ")
        print("     |")
        print("    _|___")
        print(lifes)
    elif lifes==4:
        print("      _______")
        print("     |/      |")
        print("     |      (_)")
        print("     |      \| ")
        print("     |       |")
        print("     |         ")
        print("     |")
        print("    _|___")
        print(lifes)
    elif lifes==3:
        print("      _______")
        print("     |/      |")
        print("     |      (_)")
        print("     |      \|/")
        print("     |       |")
        print("     |         ")
        print("     |")
        print("    _|___")
        print(lifes)
    elif lifes==2:
        print("      _______")
        print("     |/      |")
        print("     |      (_)")
        print("     |      \|/")
        print("     |       |")
        print("     |      /   ")
        print("     |")
        print("    _|___")
        print(lifes)
    elif lifes==1:
        print("      _______")
        print("     |/      |")
        print("     |      (_)")
        print("     |      \|/")
        print("     |       |")
        print("     |      / \. ")
        print("     |")
        print("    _|___")
        print("YOU DIED!")
        print("                            __xxxxxxxxxxxxxxxx___.")
        print("                        _gxXXXXXXXXXXXXXXXXXXXXXXXX!x_")
        print("                   __x!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!x_")
        print("                ,gXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx_")
        print("              ,gXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!_")
        print("            _!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!.")
        print("          gXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXs")
        print("        ,!XXXXXXXXXXXXXXXXXXXX XXX XX   XX XXX XXXXXXXXXXXXXXXXXXXX!.")
        print("       g!XXXXXXXXXXXXXXXXXXXXXX X XX XXX X XXX XXXXXXXXXXXXXXXXXXXXX!")
        print("      iXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX X XXX XXXXXXXXXXXXXXXXXXXXXX!")
        print("     ,XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX   XXX   XXXXXXXXXXXXXXXXXXXXXXXXx")
        print("     !XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx")
        print("   ,XXXXXXXXXXXXXXXXXXXXXXXX   XXXXX XX      XX   XXXXXXXXXXXXXXXXXXXXXXx")
        print("   !XXXXXXXXXXXXXXXXXXXXXXXX XX  XXX XX XXXXXXX XX  XXXXXXXXXXXXXXXXXXXXXi")
        print("  dXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XX XX   XXXXX XXXX XXXXXXXXXXXXXXXXXXXXX")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XX XX   XXXXX XXXX XXXXXXXXXXXXXXXXXXXXX!")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXX XX  XXX XX XXXXXXX XX  XXXXXXXXXXXXXXXXXXXXXX!")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXX XX      XX   XXXXXXXXXXXXXXXXXXXXXXXXX")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
        print("  !XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
        print("   XXXXXXXXXXXXXXXXXXXf~~~VXXXXXXXXXXXXXXXXXXXXXXXXXXvvvvvvvvXXXXXXXXXXXXXX!")
        print("   !XXXXXXXXXXXXXXXf`       'XXXXXXXXXXXXXXXXXXXXXf`          '~XXXXXXXXXXP")
        print("    vXXXXXXXXXXXX!            !XXXXXXXXXXXXXXXXXX!              !XXXXXXXXX")
        print("     XXXXXXXXXXv`              'VXXXXXXXXXXXXXXX                !XXXXXXXX!")
        print("     !XXXXXXXXX.                 YXXXXXXXXXXXXX!                XXXXXXXXX")
        print("      XXXXXXXXX!                 ,XXXXXXXXXXXXXX                VXXXXXXX!")
        print("      'XXXXXXXX!                ,!XXXX ~~XXXXXXX               iXXXXXX~")
        print("       'XXXXXXXX               ,XXXXXX   XXXXXXXX!             xXXXXXX!")
        print("        !XXXXXXX!xxxxxxs______xXXXXXXX   'YXXXXXX!          ,xXXXXXXXX")
        print("         YXXXXXXXXXXXXXXXXXXXXXXXXXXX`    VXXXXXXX!s. __gxx!XXXXXXXXXP")
        print("          XXXXXXXXXXXXXXXXXXXXXXXXXX!      'XXXXXXXXXXXXXXXXXXXXXXXXX!")
        print("          XXXXXXXXXXXXXXXXXXXXXXXXXP        'YXXXXXXXXXXXXXXXXXXXXXXX!")
        print("          XXXXXXXXXXXXXXXXXXXXXXXX!     i    !XXXXXXXXXXXXXXXXXXXXXXXX")
        print("          XXXXXXXXXXXXXXXXXXXXXXXX!     XX   !XXXXXXXXXXXXXXXXXXXXXXXX")
        print("          XXXXXXXXXXXXXXXXXXXXXXXXx_   iXX_,_dXXXXXXXXXXXXXXXXXXXXXXXX")
        print("          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXP")
        print("          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!")
        print("           ~vXvvvvXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXf")
        print("                    'VXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXvvvvvv~")
        print("                      'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX~")
        print("                  _    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXv`")
        print("                 -XX!  !XXXXXXX~XXXXXXXXXXXXXXXXXXXXXX~   Xxi")
        print("                  YXX  '~ XXXXX XXXXXXXXXXXXXXXXXXXX`     iXX`")
        print("                  !XX!    !XXX` XXXXXXXXXXXXXXXXXXXX      !XX")
        print("                  !XXX    '~Vf  YXXXXXXXXXXXXXP YXXX     !XXX")
        print("                  !XXX  ,_      !XXP YXXXfXXXX!  XXX     XXXV")
        print("                  !XXX !XX           'XXP 'YXX!       ,.!XXX!")
        print("                  !XXXi!XP  XX.                  ,_  !XXXXXX!")
        print("                  iXXXx X!  XX! !Xx.  ,.     xs.,XXi !XXXXXXf")
        print("                   XXXXXXXXXXXXXXXXX! _!XXx  dXXXXXXX.iXXXXXX")
        print("                   VXXXXXXXXXXXXXXXXXXXXXXXxxXXXXXXXXXXXXXXX!")
        print("                  YXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXV")
        print("                    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!")
        print("                    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXf")
        print("                       VXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXf")
        print("                         VXXXXXXXXXXXXXXXXXXXXXXXXXXXXv`")
        print("                          ~vXXXXXXXXXXXXXXXXXXXXXXXf`")
        print("                              ~vXXXXXXXXXXXXXXXXv~")
        print("                                 '~VvXXXXXXXV~~")
        print("                                       ~~")
        break