import random
print("888                                                           ")
print("888                                                           ")
print("888                                                           ")
print("88888b.  8888b. 88888b.  .d88b. 88888b.d88b.  8888b. 88888b.  ")
print("888  88b     88b888  88bd88P 88b888  888  88b     88b888  88b ")
print("888  888.d888888888  888888  888888  888  888.d888888888  888 ")
print("888  888888  888888  888Y88b 888888  888  888888  888888  888 ")
print("888  888 Y888888888  888  Y88888888  888  888 Y888888888  888 ")
print("                             888                              ")
print("                        Y8b d88P                              ")
print("                          Y88P   ")

words=["kokos"]
wordfind=random.choice(words)
dlugosc=len(wordfind)
lifes=10
print(wordfind)
wrd=list(wordfind)


# print("      _______")
# print("     |/      |")
# print("     |      (_)")
# print("     |      \|/")
# print("     |       |")
# print("     |      / \.")
# print("     |")
# print("    _|___")

for i in range(len(wordfind)):

    wrd[1]="_"
    
letter=input()
if letter==wordfind:
    letter = 0
else:
    lifes=lifes-1
while lifes>0:
    if lifes==9:
        print("              ")
        print("              ")
        print("               ")
        print("               ")
        print("              ")
        print("               ")
        print("      ")
        print("    _|___")
        lifes=lifes-1
        print(lifes)
        letter=input()
    elif lifes==8:
        print("              ")
        print("     |        ")
        print("     |         ")
        print("     |         ")
        print("     |        ")
        print("     |         ")
        print("     |")
        print("    _|___")
        lifes=lifes-1
        print(lifes)
        letter=input()
    elif lifes==7:
        print("      _______")
        print("     |/      |")
        print("     |         ")
        print("     |         ")
        print("     |        ")
        print("     |         ")
        print("     |")
        print("    _|___")
        lifes=lifes-1
        print(lifes)
        letter=input()
    elif lifes==6:
        print("      _______")
        print("     |/      |")
        print("     |      (_)")
        print("     |         ")
        print("     |        ")
        print("     |         ")
        print("     |")
        print("    _|___")
        lifes=lifes-1
        print(lifes)
        letter=input()
    elif lifes==5:
        print("      _______")
        print("     |/      |")
        print("     |      (_)")
        print("     |       | ")
        print("     |       |")
        print("     |         ")
        print("     |")
        print("    _|___")
        lifes=lifes-1
        print(lifes)
        letter=input()
    elif lifes==4:
        print("      _______")
        print("     |/      |")
        print("     |      (_)")
        print("     |      \| ")
        print("     |       |")
        print("     |         ")
        print("     |")
        print("    _|___")
        lifes=lifes-1
        print(lifes)
        letter=input()
    elif lifes==3:
        print("      _______")
        print("     |/      |")
        print("     |      (_)")
        print("     |      \|/")
        print("     |       |")
        print("     |         ")
        print("     |")
        print("    _|___")
        lifes=lifes-1
        print(lifes)
        letter=input()
    elif lifes==2:
        print("      _______")
        print("     |/      |")
        print("     |      (_)")
        print("     |      \|/")
        print("     |       |")
        print("     |      /   ")
        print("     |")
        print("    _|___")
        lifes=lifes-1
        print(lifes)
        letter=input()
    elif lifes==1:
        print("      _______")
        print("     |/      |")
        print("     |      (_)")
        print("     |      \|/")
        print("     |       |")
        print("     |      / \. ")
        print("     |")
        print("    _|___")
        print("YOU DIED!")
        lifes=lifes-1
        print("                            __xxxxxxxxxxxxxxxx___.")
        print("                        _gxXXXXXXXXXXXXXXXXXXXXXXXX!x_")
        print("                   __x!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!x_")
        print("                ,gXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx_")
        print("              ,gXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!_")
        print("            _!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!.")
        print("          gXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXs")
        print("        ,!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!.")
        print("       g!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!")
        print("      iXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!")
        print("     ,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx")
        print("     !XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx")
        print("   ,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx")
        print("   !XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXi")
        print("  dXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
        print("  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
        print("  !XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
        print("   XXXXXXXXXXXXXXXXXXXf~~~VXXXXXXXXXXXXXXXXXXXXXXXXXXvvvvvvvvXXXXXXXXXXXXXX!")
        print("   !XXXXXXXXXXXXXXXf`       'XXXXXXXXXXXXXXXXXXXXXf`          '~XXXXXXXXXXP")
        print("    vXXXXXXXXXXXX!            !XXXXXXXXXXXXXXXXXX!              !XXXXXXXXX")
        print("     XXXXXXXXXXv`              'VXXXXXXXXXXXXXXX                !XXXXXXXX!")
        print("     !XXXXXXXXX.                 YXXXXXXXXXXXXX!                XXXXXXXXX")
        print("      XXXXXXXXX!                 ,XXXXXXXXXXXXXX                VXXXXXXX!")
        print("      'XXXXXXXX!                ,!XXXX ~~XXXXXXX               iXXXXXX~")
        print("       'XXXXXXXX               ,XXXXXX   XXXXXXXX!             xXXXXXX!")
        print("        !XXXXXXX!xxxxxxs______xXXXXXXX   'YXXXXXX!          ,xXXXXXXXX")
        print("         YXXXXXXXXXXXXXXXXXXXXXXXXXXX`    VXXXXXXX!s. __gxx!XXXXXXXXXP")
        print("          XXXXXXXXXXXXXXXXXXXXXXXXXX!      'XXXXXXXXXXXXXXXXXXXXXXXXX!")
        print("          XXXXXXXXXXXXXXXXXXXXXXXXXP        'YXXXXXXXXXXXXXXXXXXXXXXX!")
        print("          XXXXXXXXXXXXXXXXXXXXXXXX!     i    !XXXXXXXXXXXXXXXXXXXXXXXX")
        print("          XXXXXXXXXXXXXXXXXXXXXXXX!     XX   !XXXXXXXXXXXXXXXXXXXXXXXX")
        print("          XXXXXXXXXXXXXXXXXXXXXXXXx_   iXX_,_dXXXXXXXXXXXXXXXXXXXXXXXX")
        print("          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXP")
        print("          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!")
        print("           ~vXvvvvXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXf")
        print("                    'VXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXvvvvvv~")
        print("                      'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX~")
        print("                  _    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXv`")
        print("                 -XX!  !XXXXXXX~XXXXXXXXXXXXXXXXXXXXXX~   Xxi")
        print("                  YXX  '~ XXXXX XXXXXXXXXXXXXXXXXXXX`     iXX`")
        print("                  !XX!    !XXX` XXXXXXXXXXXXXXXXXXXX      !XX")
        print("                  !XXX    '~Vf  YXXXXXXXXXXXXXP YXXX     !XXX")
        print("                  !XXX  ,_      !XXP YXXXfXXXX!  XXX     XXXV")
        print("                  !XXX !XX           'XXP 'YXX!       ,.!XXX!")
        print("                  !XXXi!XP  XX.                  ,_  !XXXXXX!")
        print("                  iXXXx X!  XX! !Xx.  ,.     xs.,XXi !XXXXXXf")
        print("                   XXXXXXXXXXXXXXXXX! _!XXx  dXXXXXXX.iXXXXXX")
        print("                   VXXXXXXXXXXXXXXXXXXXXXXXxxXXXXXXXXXXXXXXX!")
        print("                  YXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXV")
        print("                    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX!")
        print("                    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXf")
        print("                       VXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXf")
        print("                         VXXXXXXXXXXXXXXXXXXXXXXXXXXXXv`")
        print("                          ~vXXXXXXXXXXXXXXXXXXXXXXXf`")
        print("                              ~vXXXXXXXXXXXXXXXXv~")
        print("                                 '~VvXXXXXXXV~~")
        print("                                       ~~")
        break

